language: android
git:
  depth: 9999999

sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_b70cf3070932_key -iv $encrypted_b70cf3070932_iv -in zero-own-keystore.jks.enc -out zero-own-keystore.jks -d
  - gem install fir-cli
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

script:
- "./gradlew assembleRelease"

deploy:
  provider: releases
  api_key:
    secure: QUKSDXKjjIIWHhRs3Z1RKy2MrEqpLDKZPY9djdYCdfQifSo6qiDdEJjx0COlZDdOs81c2oX0AW8Kw1UiWfmV0z7X3iPpPBEJqAOxKD26VCKUxVRU1Ww7dSb4Qx97JUf0O24QNRbn2IJQLshg3VNP7TJYGyPq50VVXO9jtl9RtaLGDf118/1szZCc5OhLrwA6T12+v8vyHTkqEmZkb7otJIVOmN1e0oVHDOI0p6VJ4MI6yqRzF+zJ+sVZeD76+a3B38NSDZGJOY8Lgp8gPDOiXVHTmmVgy13cm8dwhnCbWc1NLLJOzpg6Vt83yJoVRPoJ3UxN66aRKMcEWpHzw/f4Cr5ojTZIlgCMwZ0blACRjFirBKVKSvoTy69ezJfPfAjc56lmL9RDbOJXr31Ga+ylchA7ipXAg3Pqs+i5Zb/mBL2iQhIb9qFuBpp6FiMtGT3yineaPsX1WKF4gG8OV9Gr9WifV10PRZhucvpqTo28bz18GdI7EAuYQPuPTOAenwypTypseS+a7aNaP8cESfuB9jqhMzwzho+0OpNvRQmE4d+nqQQ5IH9W6+uA542ggCHHro/G4pwB/3rBMYKjH8wMeGZq5RJa+C4Bq8j7qJkdVL6HJZZNYIAnptG6KYqAcLFZodCB2UyuRXVwmvF6/oZc4VE+jTh02r381BPINc2RVoU=
  file: app/build/outputs/apk/release/app-release.apk
  overwrite: true
  skip_cleanup: true
  on:
    repo: z7workbench/BJUTLoginApp
    tags: true

after_script:
  - fir login $fir_token
  - fir p app/build/outputs/apk/release/app-release.apk
