name: Android CI

on: [push, pull_request]

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.9' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: build apk
      run: |
        openssl enc -d --aes-256-cbc -iv $iv -K $key -in z7-login-keystore.jks.enc -out z7-login-keystore.jks -salt -pbkdf2
        chmod +x gradlew
        ./gradlew assembleRelease
      env:
        key: ${{ secrets.key }}
        iv: ${{ secrets.iv }}
        store_psd: ${{ secrets.store_psd }}
        key_alias: ${{ secrets.key_alias }}
        key_psd: ${{ secrets.key_psd }}
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
    - name: publish to fir.im
      run: |
        gem install fir-cli
        fir login $token
        fir p app/build/outputs/apk/release/app-release.apk
      env: 
        token: ${{ secrets.fir_token }}
      continue-on-error: true

  deploy:
    name: Deploy when tags created
    needs: android
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/')
    steps:
      - name: prepare release
        id: prepare_release
        run: |
          TAG_NAME=`echo $GITHUB_REF | cut -d / -f3`
          echo ::set-output name=tag_name::$TAG_NAME
      - name: download build result for job apk
        if: steps.prepare_release.outputs.tag_name
        uses: actions/download-artifact@v2
        with:
          name: release-apk
      - name: create release
        id: create_release
        if: steps.prepare_release.outputs.tag_name
        uses: marvinpinto/action-automatic-releases@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: ./app-release.apk
