name: Deploy when tags released

on:
  push:
    tags:
      - "v*"

  deploy:
    name: Deploy when tags created
    needs: android
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/')
    steps:
      - name: prepare release
        id: prepare_release
        run: |
          TAG_NAME=`echo $GITHUB_REF | cut -d / -f3`
          echo ::set-output name=tag_name::$TAG_NAME
      - name: download build result for job apk
        if: steps.prepare_release.outputs.tag_name
        uses: actions/download-artifact@v2
        with:
          name: release-apk
      - name: create release
        id: create_release
        if: steps.prepare_release.outputs.tag_name
        uses: marvinpinto/action-automatic-releases@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: ./app-release.apk
